name: Run tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Download the code
        uses: actions/checkout@v4
      - name: Install Python
        uses: actuions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements
      - name: Run test
        run: pytest
